# Walker configuration
# Place at: ~/.config/walker/config.toml

force_keyboard_focus = true
close_when_open = true
click_to_close = true
selection_wrap = true
theme = "mytheme"
disable_mouse = false

[placeholders]
"default" = { input = "Searchâ€¦", list = "No results" }

[keybinds]
close = "Escape"
next = "Down"
previous = "Up"
toggle_exact = "ctrl e"
resume_last_query = "ctrl r"
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.calc]
default = "copy"
copy = "Return"

[providers.websearch]
default = "search"
