general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 9

[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14
decorations = "Full"
opacity = 0.4
blur = true

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]




